<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.cg.addressbook.AddressBookTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2020-11-05T08:08:18" hostname="DESKTOP-AURK5V2" time="0.324">
  <properties/>
  <testcase name="givenEmployeePayrollInDB_WhenRetrieved_ShouldMatchEmployeeCount" classname="com.cg.addressbook.AddressBookTest" time="0.324"/>
  <system-out><![CDATA[Driver Loaded!!
  com.mysql.jdbc.Driver
  com.mysql.fabric.jdbc.FabricMySQLDriver
Connecting to the Database jdbc:mysql://localhost:3306/addressBookService?useSSL=false
Connection was successful
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
